#pragma once

#define NO_ACTION_ONESHOT 1
#define NO_AUTO_SHIFT_ALPHA 1

#undef TAPPING_TERM
#define TAPPING_TERM 200
#define LONG_TAPPING_TERM 490
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD

#define COMBO_COUNT 1

//#define USE_MATRIX_I2C

/* Select hand configuration */

// #define MASTER_LEFT
#define MASTER_RIGHT
// #define EE_HANDS


#ifdef RGBLIGHT_ENABLE
    #define RGBLIGHT_EFFECT_BREATHING
    #define RGBLIGHT_EFFECT_RAINBOW_MOOD
    #define RGBLIGHT_EFFECT_RAINBOW_SWIRL
    #define RGBLIGHT_EFFECT_SNAKE
    #define RGBLIGHT_EFFECT_KNIGHT
    #define RGBLIGHT_EFFECT_CHRISTMAS
    #define RGBLIGHT_EFFECT_STATIC_GRADIENT
    #define RGBLIGHT_EFFECT_RGB_TEST
    #define RGBLIGHT_EFFECT_ALTERNATING
    #define RGBLIGHT_EFFECT_TWINKLE
    #define RGBLIGHT_LIMIT_VAL 120
    #define RGBLIGHT_HUE_STEP 10
    #define RGBLIGHT_SAT_STEP 17
    #define RGBLIGHT_VAL_STEP 17
#endif

#undef RGBLED_NUM
#define RGBLED_NUM 9

#define OLED_FONT_H "keyboards/crkbd/lib/glcdfont.c"
