AUTO_SHIFT_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
MOUSEKEY_ENABLE = yes
CONVERT_TO=liatris
RGBLIGHT_ENABLE = yes # Enables QMK's RGB code
WS2812_DRIVER = vendor # Use the RP2040's PIO interface
