#define NO_AUTO_SHIFT_ALPHA 1

#undef TAPPING_TERM
#define TAPPING_TERM 200
#define LONG_TAPPING_TERM 490
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD

#define COMBO_COUNT 1

#undef WS2812_DI_PIN
#define WS2812_DI_PIN 25
#undef RGBLED_NUM
#define RGBLED_NUM 1
